titles = ['Plano Piloto DF', 'Gama - DF', 'Taguatinga - DF', 'Brazlândia - DF', 'Sobradinho - DF', 'Planaltina - DF', 'Paranoá - DF', 'Núcleo Bandeirante - DF', 'Ceilândia - DF', 'Guará - DF', 'Cruzeiro - DF', 'Samambaia - DF', 'Santa Maria - DF', 'São Sebastião - DF', 'Recanto das Emas - DF', 'Lago Sul - DF', 'Riacho Fundo I - DF', 'Lago Norte - DF', 'Candangolândia - DF', 'Águas Claras - DF', 'Riacho Fundo II - DF', 'Sudoeste / Octogonal - DF', 'Varjão - DF', 'Park Way - DF', 'SCIA - DF', 'Sobradinho II - DF', 'Jardim Botânico - DF', 'Itapoã - DF', 'SIA - DF', 'Vicente Pires - DF', 'Fercal - DF', 'Sol Nascente/Pôr do Sol - DF', 'Arniqueiras - DF']
data = {
    ('Plano Piloto - DF', 'Plano Piloto - DF'): 0,
    ('Plano Piloto - DF', 'Gama - DF'): 35067,
    ('Plano Piloto - DF', 'Taguatinga - DF'): 23696,
    ('Plano Piloto - DF', 'Brazlândia - DF'): 48548,
    ('Plano Piloto - DF', 'Sobradinho - DF'): 24059,
    ('Plano Piloto - DF', 'Planaltina - DF'): 58431,
    ('Plano Piloto - DF', 'Paranoá - DF'): 20223,
    ('Plano Piloto - DF', 'Núcleo Bandeirante - DF'): 16080,
    ('Plano Piloto - DF', 'Ceilândia - DF'): 32090,
    ('Plano Piloto - DF', 'Guará - DF'): 15876,
    ('Plano Piloto - DF', 'Cruzeiro - DF'): 2255,
    ('Plano Piloto - DF', 'Samambaia - DF'): 30389,
    ('Plano Piloto - DF', 'Santa Maria - DF'): 29688,
    ('Plano Piloto - DF', 'São Sebastião - DF'): 21998,
    ('Plano Piloto - DF', 'Recanto das Emas - DF'): 33990,
    ('Plano Piloto - DF', 'Lago Sul - DF'): 8252,
    ('Plano Piloto - DF', 'Riacho Fundo I - DF'): 21335,
    ('Plano Piloto - DF', 'Lago Norte - DF'): 14132,
    ('Plano Piloto - DF', 'Candangolândia - DF'): 16111,
    ('Plano Piloto - DF', 'Águas Claras - DF'): 19603,
    ('Plano Piloto - DF', 'Riacho Fundo II - DF'): 35481,
    ('Plano Piloto - DF', 'Sudoeste/Octogonal - DF'): 11479,
    ('Plano Piloto - DF', 'Varjão - DF'): 13352,
    ('Plano Piloto - DF', 'Park Way - DF'): 15779,
    ('Plano Piloto - DF', 'SCIA - DF'): 13047,
    ('Plano Piloto - DF', 'Sobradinho II - DF'): 32961,
    ('Plano Piloto - DF', 'Jardim Botânico - DF'): 17068,
    ('Plano Piloto - DF', 'Itapoã - DF'): 24523,
    ('Plano Piloto - DF', 'SIA - DF'): 2255,
    ('Plano Piloto - DF', 'Vicente Pires - DF'): 17714,
    ('Plano Piloto - DF', 'Fercal - DF'): 28325,
    ('Plano Piloto - DF', 'Sol Nascente/Pôr do Sol - DF'): 6935,
    ('Plano Piloto - DF', 'Arniqueiras - DF'): 19404,
    ('Gama - DF', 'Plano Piloto - DF'): 34737,
    ('Gama - DF', 'Gama - DF'): 0,
    ('Gama - DF', 'Taguatinga - DF'): 31846,
    ('Gama - DF', 'Brazlândia - DF'): 61549,
    ('Gama - DF', 'Sobradinho - DF'): 54101,
    ('Gama - DF', 'Planaltina - DF'): 88473,
    ('Gama - DF', 'Paranoá - DF'): 53138,
    ('Gama - DF', 'Núcleo Bandeirante - DF'): 24217,
    ('Gama - DF', 'Ceilândia - DF'): 31277,
    ('Gama - DF', 'Guará - DF'): 30510,
    ('Gama - DF', 'Cruzeiro - DF'): 34074,
    ('Gama - DF', 'Samambaia - DF'): 24235,
    ('Gama - DF', 'Santa Maria - DF'): 11588,
    ('Gama - DF', 'São Sebastião - DF'): 42624,
    ('Gama - DF', 'Recanto das Emas - DF'): 15886,
    ('Gama - DF', 'Lago Sul - DF'): 31798,
    ('Gama - DF', 'Riacho Fundo I - DF'): 24318,
    ('Gama - DF', 'Lago Norte - DF'): 45259,
    ('Gama - DF', 'Candangolândia - DF'): 24093,
    ('Gama - DF', 'Águas Claras - DF'): 28857,
    ('Gama - DF', 'Riacho Fundo II - DF'): 17377,
    ('Gama - DF', 'Sudoeste/Octogonal - DF'): 30147,
    ('Gama - DF', 'Varjão - DF'): 44479,
    ('Gama - DF', 'Park Way - DF'): 19617,
    ('Gama - DF', 'SCIA - DF'): 34465,
    ('Gama - DF', 'Sobradinho II - DF'): 63002,
    ('Gama - DF', 'Jardim Botânico - DF'): 42579,
    ('Gama - DF', 'Itapoã - DF'): 57438,
    ('Gama - DF', 'SIA - DF'): 34074,
    ('Gama - DF', 'Vicente Pires - DF'): 38212,
    ('Gama - DF', 'Fercal - DF'): 58367,
    ('Gama - DF', 'Sol Nascente/Pôr do Sol - DF'): 29577,
    ('Gama - DF', 'Arniqueiras - DF'): 32314,
    ('Taguatinga - DF', 'Plano Piloto - DF'): 22798,
    ('Taguatinga - DF', 'Gama - DF'): 29814,
    ('Taguatinga - DF', 'Taguatinga - DF'): 0,
    ('Taguatinga - DF', 'Brazlândia - DF'): 31501,
    ('Taguatinga - DF', 'Sobradinho - DF'): 38203,
    ('Taguatinga - DF', 'Planaltina - DF'): 72575,
    ('Taguatinga - DF', 'Paranoá - DF'): 41375,
    ('Taguatinga - DF', 'Núcleo Bandeirante - DF'): 15365,
    ('Taguatinga - DF', 'Ceilândia - DF'): 6824,
    ('Taguatinga - DF', 'Guará - DF'): 13810,
    ('Taguatinga - DF', 'Cruzeiro - DF'): 23632,
    ('Taguatinga - DF', 'Samambaia - DF'): 10731,
    ('Taguatinga - DF', 'Santa Maria - DF'): 28819,
    ('Taguatinga - DF', 'São Sebastião - DF'): 43595,
    ('Taguatinga - DF', 'Recanto das Emas - DF'): 16210,
    ('Taguatinga - DF', 'Lago Sul - DF'): 27467,
    ('Taguatinga - DF', 'Riacho Fundo I - DF'): 10710,
    ('Taguatinga - DF', 'Lago Norte - DF'): 29361,
    ('Taguatinga - DF', 'Candangolândia - DF'): 18297,
    ('Taguatinga - DF', 'Águas Claras - DF'): 7439,
    ('Taguatinga - DF', 'Riacho Fundo II - DF'): 14820,
    ('Taguatinga - DF', 'Sudoeste/Octogonal - DF'): 17203,
    ('Taguatinga - DF', 'Varjão - DF'): 28581,
    ('Taguatinga - DF', 'Park Way - DF'): 24200,
    ('Taguatinga - DF', 'SCIA - DF'): 11948,
    ('Taguatinga - DF', 'Sobradinho II - DF'): 47105,
    ('Taguatinga - DF', 'Jardim Botânico - DF'): 38665,
    ('Taguatinga - DF', 'Itapoã - DF'): 43689,
    ('Taguatinga - DF', 'SIA - DF'): 23632,
    ('Taguatinga - DF', 'Vicente Pires - DF'): 6254,
    ('Taguatinga - DF', 'Fercal - DF'): 42469,
    ('Taguatinga - DF', 'Sol Nascente/Pôr do Sol - DF'): 20602,
    ('Taguatinga - DF', 'Arniqueiras - DF'): 8398,
    ('Brazlândia - DF', 'Plano Piloto - DF'): 48282,
    ('Brazlândia - DF', 'Gama - DF'): 59336,
    ('Brazlândia - DF', 'Taguatinga - DF'): 31141,
    ('Brazlândia - DF', 'Brazlândia - DF'): 0,
    ('Brazlândia - DF', 'Sobradinho - DF'): 56383,
    ('Brazlândia - DF', 'Planaltina - DF'): 90755,
    ('Brazlândia - DF', 'Paranoá - DF'): 66860,
    ('Brazlândia - DF', 'Núcleo Bandeirante - DF'): 44886,
    ('Brazlândia - DF', 'Ceilândia - DF'): 30123,
    ('Brazlândia - DF', 'Guará - DF'): 42047,
    ('Brazlândia - DF', 'Cruzeiro - DF'): 49117,
    ('Brazlândia - DF', 'Samambaia - DF'): 36122,
    ('Brazlândia - DF', 'Santa Maria - DF'): 66616,
    ('Brazlândia - DF', 'São Sebastião - DF'): 69079,
    ('Brazlândia - DF', 'Recanto das Emas - DF'): 45732,
    ('Brazlândia - DF', 'Lago Sul - DF'): 57524,
    ('Brazlândia - DF', 'Riacho Fundo I - DF'): 40231,
    ('Brazlândia - DF', 'Lago Norte - DF'): 54846,
    ('Brazlândia - DF', 'Candangolândia - DF'): 51293,
    ('Brazlândia - DF', 'Águas Claras - DF'): 36961,
    ('Brazlândia - DF', 'Riacho Fundo II - DF'): 44341,
    ('Brazlândia - DF', 'Sudoeste/Octogonal - DF'): 44354,
    ('Brazlândia - DF', 'Varjão - DF'): 54066,
    ('Brazlândia - DF', 'Park Way - DF'): 52707,
    ('Brazlândia - DF', 'SCIA - DF'): 37432,
    ('Brazlândia - DF', 'Sobradinho II - DF'): 65268,
    ('Brazlândia - DF', 'Jardim Botânico - DF'): 64149,
    ('Brazlândia - DF', 'Itapoã - DF'): 61876,
    ('Brazlândia - DF', 'SIA - DF'): 49117,
    ('Brazlândia - DF', 'Vicente Pires - DF'): 34222,
    ('Brazlândia - DF', 'Fercal - DF'): 60656,
    ('Brazlândia - DF', 'Sol Nascente/Pôr do Sol - DF'): 49312,
    ('Brazlândia - DF', 'Arniqueiras - DF'): 37920,
    ('Sobradinho - DF', 'Plano Piloto - DF'): 23802,
    ('Sobradinho - DF', 'Gama - DF'): 53593,
    ('Sobradinho - DF', 'Taguatinga - DF'): 38211,
    ('Sobradinho - DF', 'Brazlândia - DF'): 63062,
    ('Sobradinho - DF', 'Sobradinho - DF'): 0,
    ('Sobradinho - DF', 'Planaltina - DF'): 38049,
    ('Sobradinho - DF', 'Paranoá - DF'): 20988,
    ('Sobradinho - DF', 'Núcleo Bandeirante - DF'): 33851,
    ('Sobradinho - DF', 'Ceilândia - DF'): 46605,
    ('Sobradinho - DF', 'Guará - DF'): 33369,
    ('Sobradinho - DF', 'Cruzeiro - DF'): 23178,
    ('Sobradinho - DF', 'Samambaia - DF'): 47651,
    ('Sobradinho - DF', 'Santa Maria - DF'): 48214,
    ('Sobradinho - DF', 'São Sebastião - DF'): 43131,
    ('Sobradinho - DF', 'Recanto das Emas - DF'): 48050,
    ('Sobradinho - DF', 'Lago Sul - DF'): 33515,
    ('Sobradinho - DF', 'Riacho Fundo I - DF'): 38597,
    ('Sobradinho - DF', 'Lago Norte - DF'): 19785,
    ('Sobradinho - DF', 'Candangolândia - DF'): 32892,
    ('Sobradinho - DF', 'Águas Claras - DF'): 37424,
    ('Sobradinho - DF', 'Riacho Fundo II - DF'): 46659,
    ('Sobradinho - DF', 'Sudoeste/Octogonal - DF'): 25952,
    ('Sobradinho - DF', 'Varjão - DF'): 14604,
    ('Sobradinho - DF', 'Park Way - DF'): 34305,
    ('Sobradinho - DF', 'SCIA - DF'): 27561,
    ('Sobradinho - DF', 'Sobradinho II - DF'): 10994,
    ('Sobradinho - DF', 'Jardim Botânico - DF'): 38201,
    ('Sobradinho - DF', 'Itapoã - DF'): 18269,
    ('Sobradinho - DF', 'SIA - DF'): 23178,
    ('Sobradinho - DF', 'Vicente Pires - DF'): 34234,
    ('Sobradinho - DF', 'Fercal - DF'): 14709,
    ('Sobradinho - DF', 'Sol Nascente/Pôr do Sol - DF'): 30911,
    ('Sobradinho - DF', 'Arniqueiras - DF'): 37225,
    ('Planaltina - DF', 'Plano Piloto - DF'): 58011,
    ('Planaltina - DF', 'Gama - DF'): 87802,
    ('Planaltina - DF', 'Taguatinga - DF'): 72419,
    ('Planaltina - DF', 'Brazlândia - DF'): 97271,
    ('Planaltina - DF', 'Sobradinho - DF'): 36780,
    ('Planaltina - DF', 'Planaltina - DF'): 0,
    ('Planaltina - DF', 'Paranoá - DF'): 55196,
    ('Planaltina - DF', 'Núcleo Bandeirante - DF'): 68060,
    ('Planaltina - DF', 'Ceilândia - DF'): 80814,
    ('Planaltina - DF', 'Guará - DF'): 67578,
    ('Planaltina - DF', 'Cruzeiro - DF'): 57386,
    ('Planaltina - DF', 'Samambaia - DF'): 81860,
    ('Planaltina - DF', 'Santa Maria - DF'): 82423,
    ('Planaltina - DF', 'São Sebastião - DF'): 77340,
    ('Planaltina - DF', 'Recanto das Emas - DF'): 82258,
    ('Planaltina - DF', 'Lago Sul - DF'): 67724,
    ('Planaltina - DF', 'Riacho Fundo I - DF'): 72806,
    ('Planaltina - DF', 'Lago Norte - DF'): 53994,
    ('Planaltina - DF', 'Candangolândia - DF'): 67100,
    ('Planaltina - DF', 'Águas Claras - DF'): 71632,
    ('Planaltina - DF', 'Riacho Fundo II - DF'): 80868,
    ('Planaltina - DF', 'Sudoeste/Octogonal - DF'): 60161,
    ('Planaltina - DF', 'Varjão - DF'): 48813,
    ('Planaltina - DF', 'Park Way - DF'): 68514,
    ('Planaltina - DF', 'SCIA - DF'): 61770,
    ('Planaltina - DF', 'Sobradinho II - DF'): 43597,
    ('Planaltina - DF', 'Jardim Botânico - DF'): 72410,
    ('Planaltina - DF', 'Itapoã - DF'): 48673,
    ('Planaltina - DF', 'SIA - DF'): 57386,
    ('Planaltina - DF', 'Vicente Pires - DF'): 68443,
    ('Planaltina - DF', 'Fercal - DF'): 48918,
    ('Planaltina - DF', 'Sol Nascente/Pôr do Sol - DF'): 65119,
    ('Planaltina - DF', 'Arniqueiras - DF'): 71433,
    ('Paranoá - DF', 'Plano Piloto - DF'): 19639,
    ('Paranoá - DF', 'Gama - DF'): 53635,
    ('Paranoá - DF', 'Taguatinga - DF'): 41941,
    ('Paranoá - DF', 'Brazlândia - DF'): 66793,
    ('Paranoá - DF', 'Sobradinho - DF'): 19735,
    ('Paranoá - DF', 'Planaltina - DF'): 50754,
    ('Paranoá - DF', 'Paranoá - DF'): 0,
    ('Paranoá - DF', 'Núcleo Bandeirante - DF'): 32645,
    ('Paranoá - DF', 'Ceilândia - DF'): 50335,
    ('Paranoá - DF', 'Guará - DF'): 32021,
    ('Paranoá - DF', 'Cruzeiro - DF'): 19560,
    ('Paranoá - DF', 'Samambaia - DF'): 46534,
    ('Paranoá - DF', 'Santa Maria - DF'): 44693,
    ('Paranoá - DF', 'São Sebastião - DF'): 22380,
    ('Paranoá - DF', 'Recanto das Emas - DF'): 52354,
    ('Paranoá - DF', 'Lago Sul - DF'): 19325,
    ('Paranoá - DF', 'Riacho Fundo I - DF'): 37480,
    ('Paranoá - DF', 'Lago Norte - DF'): 19228,
    ('Paranoá - DF', 'Candangolândia - DF'): 31774,
    ('Paranoá - DF', 'Águas Claras - DF'): 41154,
    ('Paranoá - DF', 'Riacho Fundo II - DF'): 53845,
    ('Paranoá - DF', 'Sudoeste/Octogonal - DF'): 29682,
    ('Paranoá - DF', 'Varjão - DF'): 14301,
    ('Paranoá - DF', 'Park Way - DF'): 33188,
    ('Paranoá - DF', 'SCIA - DF'): 31291,
    ('Paranoá - DF', 'Sobradinho II - DF'): 28637,
    ('Paranoá - DF', 'Jardim Botânico - DF'): 17450,
    ('Paranoá - DF', 'Itapoã - DF'): 5070,
    ('Paranoá - DF', 'SIA - DF'): 19560,
    ('Paranoá - DF', 'Vicente Pires - DF'): 37965,
    ('Paranoá - DF', 'Fercal - DF'): 27526,
    ('Paranoá - DF', 'Sol Nascente/Pôr do Sol - DF'): 26515,
    ('Paranoá - DF', 'Arniqueiras - DF'): 40955,
    ('Núcleo Bandeirante - DF', 'Plano Piloto - DF'): 16051,
    ('Núcleo Bandeirante - DF', 'Gama - DF'): 24144,
    ('Núcleo Bandeirante - DF', 'Taguatinga - DF'): 16213,
    ('Núcleo Bandeirante - DF', 'Brazlândia - DF'): 53016,
    ('Núcleo Bandeirante - DF', 'Sobradinho - DF'): 33362,
    ('Núcleo Bandeirante - DF', 'Planaltina - DF'): 67734,
    ('Núcleo Bandeirante - DF', 'Paranoá - DF'): 30818,
    ('Núcleo Bandeirante - DF', 'Núcleo Bandeirante - DF'): 0,
    ('Núcleo Bandeirante - DF', 'Ceilândia - DF'): 23014,
    ('Núcleo Bandeirante - DF', 'Guará - DF'): 9771,
    ('Núcleo Bandeirante - DF', 'Cruzeiro - DF'): 15388,
    ('Núcleo Bandeirante - DF', 'Samambaia - DF'): 15972,
    ('Núcleo Bandeirante - DF', 'Santa Maria - DF'): 18765,
    ('Núcleo Bandeirante - DF', 'São Sebastião - DF'): 32592,
    ('Núcleo Bandeirante - DF', 'Recanto das Emas - DF'): 16370,
    ('Núcleo Bandeirante - DF', 'Lago Sul - DF'): 14203,
    ('Núcleo Bandeirante - DF', 'Riacho Fundo I - DF'): 6917,
    ('Núcleo Bandeirante - DF', 'Lago Norte - DF'): 24520,
    ('Núcleo Bandeirante - DF', 'Candangolândia - DF'): 3272,
    ('Núcleo Bandeirante - DF', 'Águas Claras - DF'): 10556,
    ('Núcleo Bandeirante - DF', 'Riacho Fundo II - DF'): 14980,
    ('Núcleo Bandeirante - DF', 'Sudoeste/Octogonal - DF'): 9408,
    ('Núcleo Bandeirante - DF', 'Varjão - DF'): 23740,
    ('Núcleo Bandeirante - DF', 'Park Way - DF'): 4856,
    ('Núcleo Bandeirante - DF', 'SCIA - DF'): 13727,
    ('Núcleo Bandeirante - DF', 'Sobradinho II - DF'): 42264,
    ('Núcleo Bandeirante - DF', 'Jardim Botânico - DF'): 27662,
    ('Núcleo Bandeirante - DF', 'Itapoã - DF'): 35117,
    ('Núcleo Bandeirante - DF', 'SIA - DF'): 15388,
    ('Núcleo Bandeirante - DF', 'Vicente Pires - DF'): 17474,
    ('Núcleo Bandeirante - DF', 'Fercal - DF'): 37628,
    ('Núcleo Bandeirante - DF', 'Sol Nascente/Pôr do Sol - DF'): 10890,
    ('Núcleo Bandeirante - DF', 'Arniqueiras - DF'): 9560,
    ('Ceilândia - DF', 'Plano Piloto - DF'): 32088,
    ('Ceilândia - DF', 'Gama - DF'): 31177,
    ('Ceilândia - DF', 'Taguatinga - DF'): 6818,
    ('Ceilândia - DF', 'Brazlândia - DF'): 27771,
    ('Ceilândia - DF', 'Sobradinho - DF'): 47494,
    ('Ceilândia - DF', 'Planaltina - DF'): 81866,
    ('Ceilândia - DF', 'Paranoá - DF'): 50666,
    ('Ceilândia - DF', 'Núcleo Bandeirante - DF'): 23119,
    ('Ceilândia - DF', 'Ceilândia - DF'): 0,
    ('Ceilândia - DF', 'Guará - DF'): 19578,
    ('Ceilândia - DF', 'Cruzeiro - DF'): 32923,
    ('Ceilândia - DF', 'Samambaia - DF'): 7500,
    ('Ceilândia - DF', 'Santa Maria - DF'): 30182,
    ('Ceilândia - DF', 'São Sebastião - DF'): 57626,
    ('Ceilândia - DF', 'Recanto das Emas - DF'): 17573,
    ('Ceilândia - DF', 'Lago Sul - DF'): 33235,
    ('Ceilândia - DF', 'Riacho Fundo I - DF'): 18464,
    ('Ceilândia - DF', 'Lago Norte - DF'): 38652,
    ('Ceilândia - DF', 'Candangolândia - DF'): 26051,
    ('Ceilândia - DF', 'Águas Claras - DF'): 13207,
    ('Ceilândia - DF', 'Riacho Fundo II - DF'): 16183,
    ('Ceilândia - DF', 'Sudoeste/Octogonal - DF'): 28160,
    ('Ceilândia - DF', 'Varjão - DF'): 37872,
    ('Ceilândia - DF', 'Park Way - DF'): 27635,
    ('Ceilândia - DF', 'SCIA - DF'): 21239,
    ('Ceilândia - DF', 'Sobradinho II - DF'): 56396,
    ('Ceilândia - DF', 'Jardim Botânico - DF'): 47956,
    ('Ceilândia - DF', 'Itapoã - DF'): 52980,
    ('Ceilândia - DF', 'SIA - DF'): 32923,
    ('Ceilândia - DF', 'Vicente Pires - DF'): 18028,
    ('Ceilândia - DF', 'Fercal - DF'): 51760,
    ('Ceilândia - DF', 'Sol Nascente/Pôr do Sol - DF'): 26370,
    ('Ceilândia - DF', 'Arniqueiras - DF'): 14166,
    ('Guará - DF', 'Plano Piloto - DF'): 13630,
    ('Guará - DF', 'Gama - DF'): 29786,
    ('Guará - DF', 'Taguatinga - DF'): 14013,
    ('Guará - DF', 'Brazlândia - DF'): 42285,
    ('Guará - DF', 'Sobradinho - DF'): 31412,
    ('Guará - DF', 'Planaltina - DF'): 65784,
    ('Guará - DF', 'Paranoá - DF'): 31647,
    ('Guará - DF', 'Núcleo Bandeirante - DF'): 7257,
    ('Guará - DF', 'Ceilândia - DF'): 19697,
    ('Guará - DF', 'Guará - DF'): 0,
    ('Guará - DF', 'Cruzeiro - DF'): 16217,
    ('Guará - DF', 'Samambaia - DF'): 20852,
    ('Guará - DF', 'Santa Maria - DF'): 24406,
    ('Guará - DF', 'São Sebastião - DF'): 33422,
    ('Guará - DF', 'Recanto das Emas - DF'): 21250,
    ('Guará - DF', 'Lago Sul - DF'): 15032,
    ('Guará - DF', 'Riacho Fundo I - DF'): 11797,
    ('Guará - DF', 'Lago Norte - DF'): 22570,
    ('Guará - DF', 'Candangolândia - DF'): 9084,
    ('Guará - DF', 'Águas Claras - DF'): 10158,
    ('Guará - DF', 'Riacho Fundo II - DF'): 19860,
    ('Guará - DF', 'Sudoeste/Octogonal - DF'): 7459,
    ('Guará - DF', 'Varjão - DF'): 21790,
    ('Guará - DF', 'Park Way - DF'): 10497,
    ('Guará - DF', 'SCIA - DF'): 7053,
    ('Guará - DF', 'Sobradinho II - DF'): 40314,
    ('Guará - DF', 'Jardim Botânico - DF'): 28492,
    ('Guará - DF', 'Itapoã - DF'): 36898,
    ('Guará - DF', 'SIA - DF'): 16217,
    ('Guará - DF', 'Vicente Pires - DF'): 8269,
    ('Guará - DF', 'Fercal - DF'): 35678,
    ('Guará - DF', 'Sol Nascente/Pôr do Sol - DF'): 11720,
    ('Guará - DF', 'Arniqueiras - DF'): 9959,
    ('Cruzeiro - DF', 'Plano Piloto - DF'): 2252,
    ('Cruzeiro - DF', 'Gama - DF'): 35011,
    ('Cruzeiro - DF', 'Taguatinga - DF'): 24775,
    ('Cruzeiro - DF', 'Brazlândia - DF'): 49627,
    ('Cruzeiro - DF', 'Sobradinho - DF'): 23008,
    ('Cruzeiro - DF', 'Planaltina - DF'): 57380,
    ('Cruzeiro - DF', 'Paranoá - DF'): 21446,
    ('Cruzeiro - DF', 'Núcleo Bandeirante - DF'): 16024,
    ('Cruzeiro - DF', 'Ceilândia - DF'): 33170,
    ('Cruzeiro - DF', 'Guará - DF'): 15820,
    ('Cruzeiro - DF', 'Cruzeiro - DF'): 0,
    ('Cruzeiro - DF', 'Samambaia - DF'): 30333,
    ('Cruzeiro - DF', 'Santa Maria - DF'): 29632,
    ('Cruzeiro - DF', 'São Sebastião - DF'): 23221,
    ('Cruzeiro - DF', 'Recanto das Emas - DF'): 33934,
    ('Cruzeiro - DF', 'Lago Sul - DF'): 9522,
    ('Cruzeiro - DF', 'Riacho Fundo I - DF'): 21279,
    ('Cruzeiro - DF', 'Lago Norte - DF'): 13080,
    ('Cruzeiro - DF', 'Candangolândia - DF'): 16054,
    ('Cruzeiro - DF', 'Águas Claras - DF'): 22658,
    ('Cruzeiro - DF', 'Riacho Fundo II - DF'): 35424,
    ('Cruzeiro - DF', 'Sudoeste/Octogonal - DF'): 12558,
    ('Cruzeiro - DF', 'Varjão - DF'): 12300,
    ('Cruzeiro - DF', 'Park Way - DF'): 15723,
    ('Cruzeiro - DF', 'SCIA - DF'): 14126,
    ('Cruzeiro - DF', 'Sobradinho II - DF'): 31909,
    ('Cruzeiro - DF', 'Jardim Botânico - DF'): 18291,
    ('Cruzeiro - DF', 'Itapoã - DF'): 26553,
    ('Cruzeiro - DF', 'SIA - DF'): 0,
    ('Cruzeiro - DF', 'Vicente Pires - DF'): 20769,
    ('Cruzeiro - DF', 'Fercal - DF'): 27274,
    ('Cruzeiro - DF', 'Sol Nascente/Pôr do Sol - DF'): 6878,
    ('Cruzeiro - DF', 'Arniqueiras - DF'): 22459,
    ('Samambaia - DF', 'Plano Piloto - DF'): 31615,
    ('Samambaia - DF', 'Gama - DF'): 23963,
    ('Samambaia - DF', 'Taguatinga - DF'): 11425,
    ('Samambaia - DF', 'Brazlândia - DF'): 34157,
    ('Samambaia - DF', 'Sobradinho - DF'): 48927,
    ('Samambaia - DF', 'Planaltina - DF'): 83299,
    ('Samambaia - DF', 'Paranoá - DF'): 46382,
    ('Samambaia - DF', 'Núcleo Bandeirante - DF'): 15905,
    ('Samambaia - DF', 'Ceilândia - DF'): 7028,
    ('Samambaia - DF', 'Guará - DF'): 20439,
    ('Samambaia - DF', 'Cruzeiro - DF'): 30953,
    ('Samambaia - DF', 'Samambaia - DF'): 0,
    ('Samambaia - DF', 'Santa Maria - DF'): 22968,
    ('Samambaia - DF', 'São Sebastião - DF'): 50412,
    ('Samambaia - DF', 'Recanto das Emas - DF'): 10359,
    ('Samambaia - DF', 'Lago Sul - DF'): 29767,
    ('Samambaia - DF', 'Riacho Fundo I - DF'): 11250,
    ('Samambaia - DF', 'Lago Norte - DF'): 40085,
    ('Samambaia - DF', 'Candangolândia - DF'): 18837,
    ('Samambaia - DF', 'Águas Claras - DF'): 15790,
    ('Samambaia - DF', 'Riacho Fundo II - DF'): 8969,
    ('Samambaia - DF', 'Sudoeste/Octogonal - DF'): 24973,
    ('Samambaia - DF', 'Varjão - DF'): 39305,
    ('Samambaia - DF', 'Park Way - DF'): 20421,
    ('Samambaia - DF', 'SCIA - DF'): 21977,
    ('Samambaia - DF', 'Sobradinho II - DF'): 57829,
    ('Samambaia - DF', 'Jardim Botânico - DF'): 43227,
    ('Samambaia - DF', 'Itapoã - DF'): 50682,
    ('Samambaia - DF', 'SIA - DF'): 30953,
    ('Samambaia - DF', 'Vicente Pires - DF'): 17108,
    ('Samambaia - DF', 'Fercal - DF'): 53193,
    ('Samambaia - DF', 'Sol Nascente/Pôr do Sol - DF'): 26455,
    ('Samambaia - DF', 'Arniqueiras - DF'): 16500,
    ('Santa Maria - DF', 'Plano Piloto - DF'): 29221,
    ('Santa Maria - DF', 'Gama - DF'): 11541,
    ('Santa Maria - DF', 'Taguatinga - DF'): 38440,
    ('Santa Maria - DF', 'Brazlândia - DF'): 68238,
    ('Santa Maria - DF', 'Sobradinho - DF'): 48584,
    ('Santa Maria - DF', 'Planaltina - DF'): 82956,
    ('Santa Maria - DF', 'Paranoá - DF'): 43634,
    ('Santa Maria - DF', 'Núcleo Bandeirante - DF'): 18701,
    ('Santa Maria - DF', 'Ceilândia - DF'): 30743,
    ('Santa Maria - DF', 'Guará - DF'): 24993,
    ('Santa Maria - DF', 'Cruzeiro - DF'): 28558,
    ('Santa Maria - DF', 'Samambaia - DF'): 23700,
    ('Santa Maria - DF', 'Santa Maria - DF'): 0,
    ('Santa Maria - DF', 'São Sebastião - DF'): 33120,
    ('Santa Maria - DF', 'Recanto das Emas - DF'): 15352,
    ('Santa Maria - DF', 'Lago Sul - DF'): 26282,
    ('Santa Maria - DF', 'Riacho Fundo I - DF'): 25283,
    ('Santa Maria - DF', 'Lago Norte - DF'): 39742,
    ('Santa Maria - DF', 'Candangolândia - DF'): 18577,
    ('Santa Maria - DF', 'Águas Claras - DF'): 27793,
    ('Santa Maria - DF', 'Riacho Fundo II - DF'): 16843,
    ('Santa Maria - DF', 'Sudoeste/Octogonal - DF'): 24630,
    ('Santa Maria - DF', 'Varjão - DF'): 38962,
    ('Santa Maria - DF', 'Park Way - DF'): 14100,
    ('Santa Maria - DF', 'SCIA - DF'): 28948,
    ('Santa Maria - DF', 'Sobradinho II - DF'): 57486,
    ('Santa Maria - DF', 'Jardim Botânico - DF'): 33075,
    ('Santa Maria - DF', 'Itapoã - DF'): 47934,
    ('Santa Maria - DF', 'SIA - DF'): 28558,
    ('Santa Maria - DF', 'Vicente Pires - DF'): 32696,
    ('Santa Maria - DF', 'Fercal - DF'): 52850,
    ('Santa Maria - DF', 'Sol Nascente/Pôr do Sol - DF'): 24060,
    ('Santa Maria - DF', 'Arniqueiras - DF'): 26797,
    ('São Sebastião - DF', 'Plano Piloto - DF'): 21353,
    ('São Sebastião - DF', 'Gama - DF'): 42746,
    ('São Sebastião - DF', 'Taguatinga - DF'): 45677,
    ('São Sebastião - DF', 'Brazlândia - DF'): 70062,
    ('São Sebastião - DF', 'Sobradinho - DF'): 42214,
    ('São Sebastião - DF', 'Planaltina - DF'): 76586,
    ('São Sebastião - DF', 'Paranoá - DF'): 21655,
    ('São Sebastião - DF', 'Núcleo Bandeirante - DF'): 29911,
    ('São Sebastião - DF', 'Ceilândia - DF'): 51361,
    ('São Sebastião - DF', 'Guará - DF'): 33735,
    ('São Sebastião - DF', 'Cruzeiro - DF'): 21275,
    ('São Sebastião - DF', 'Samambaia - DF'): 49814,
    ('São Sebastião - DF', 'Santa Maria - DF'): 33804,
    ('São Sebastião - DF', 'São Sebastião - DF'): 0,
    ('São Sebastião - DF', 'Recanto das Emas - DF'): 41466,
    ('São Sebastião - DF', 'Lago Sul - DF'): 18315,
    ('São Sebastião - DF', 'Riacho Fundo I - DF'): 39194,
    ('São Sebastião - DF', 'Lago Norte - DF'): 32286,
    ('São Sebastião - DF', 'Candangolândia - DF'): 33489,
    ('São Sebastião - DF', 'Águas Claras - DF'): 41822,
    ('São Sebastião - DF', 'Riacho Fundo II - DF'): 42956,
    ('São Sebastião - DF', 'Sudoeste/Octogonal - DF'): 33627,
    ('São Sebastião - DF', 'Varjão - DF'): 31506,
    ('São Sebastião - DF', 'Park Way - DF'): 40227,
    ('São Sebastião - DF', 'SCIA - DF'): 34560,
    ('São Sebastião - DF', 'Sobradinho II - DF'): 51115,
    ('São Sebastião - DF', 'Jardim Botânico - DF'): 11095,
    ('São Sebastião - DF', 'Itapoã - DF'): 25954,
    ('São Sebastião - DF', 'SIA - DF'): 21275,
    ('São Sebastião - DF', 'Vicente Pires - DF'): 39933,
    ('São Sebastião - DF', 'Fercal - DF'): 46480,
    ('São Sebastião - DF', 'Sol Nascente/Pôr do Sol - DF'): 28230,
    ('São Sebastião - DF', 'Arniqueiras - DF'): 40708,
    ('Recanto das Emas - DF', 'Plano Piloto - DF'): 33278,
    ('Recanto das Emas - DF', 'Gama - DF'): 14541,
    ('Recanto das Emas - DF', 'Taguatinga - DF'): 18383,
    ('Recanto das Emas - DF', 'Brazlândia - DF'): 48086,
    ('Recanto das Emas - DF', 'Sobradinho - DF'): 52641,
    ('Recanto das Emas - DF', 'Planaltina - DF'): 87013,
    ('Recanto das Emas - DF', 'Paranoá - DF'): 51504,
    ('Recanto das Emas - DF', 'Núcleo Bandeirante - DF'): 15509,
    ('Recanto das Emas - DF', 'Ceilândia - DF'): 17814,
    ('Recanto das Emas - DF', 'Guará - DF'): 29050,
    ('Recanto das Emas - DF', 'Cruzeiro - DF'): 32615,
    ('Recanto das Emas - DF', 'Samambaia - DF'): 10771,
    ('Recanto das Emas - DF', 'Santa Maria - DF'): 13546,
    ('Recanto das Emas - DF', 'São Sebastião - DF'): 40990,
    ('Recanto das Emas - DF', 'Recanto das Emas - DF'): 0,
    ('Recanto das Emas - DF', 'Lago Sul - DF'): 30339,
    ('Recanto das Emas - DF', 'Riacho Fundo I - DF'): 10854,
    ('Recanto das Emas - DF', 'Lago Norte - DF'): 43799,
    ('Recanto das Emas - DF', 'Candangolândia - DF'): 18441,
    ('Recanto das Emas - DF', 'Águas Claras - DF'): 15394,
    ('Recanto das Emas - DF', 'Riacho Fundo II - DF'): 3914,
    ('Recanto das Emas - DF', 'Sudoeste/Octogonal - DF'): 28687,
    ('Recanto das Emas - DF', 'Varjão - DF'): 43019,
    ('Recanto das Emas - DF', 'Park Way - DF'): 18158,
    ('Recanto das Emas - DF', 'SCIA - DF'): 26373,
    ('Recanto das Emas - DF', 'Sobradinho II - DF'): 61543,
    ('Recanto das Emas - DF', 'Jardim Botânico - DF'): 40945,
    ('Recanto das Emas - DF', 'Itapoã - DF'): 55804,
    ('Recanto das Emas - DF', 'SIA - DF'): 32615,
    ('Recanto das Emas - DF', 'Vicente Pires - DF'): 22752,
    ('Recanto das Emas - DF', 'Fercal - DF'): 56907,
    ('Recanto das Emas - DF', 'Sol Nascente/Pôr do Sol - DF'): 28117,
    ('Recanto das Emas - DF', 'Arniqueiras - DF'): 16105,
    ('Lago Sul - DF', 'Plano Piloto - DF'): 7609,
    ('Lago Sul - DF', 'Gama - DF'): 31927,
    ('Lago Sul - DF', 'Taguatinga - DF'): 27134,
    ('Lago Sul - DF', 'Brazlândia - DF'): 55405,
    ('Lago Sul - DF', 'Sobradinho - DF'): 29780,
    ('Lago Sul - DF', 'Planaltina - DF'): 64152,
    ('Lago Sul - DF', 'Paranoá - DF'): 20534,
    ('Lago Sul - DF', 'Núcleo Bandeirante - DF'): 12940,
    ('Lago Sul - DF', 'Ceilândia - DF'): 32817,
    ('Lago Sul - DF', 'Guará - DF'): 15191,
    ('Lago Sul - DF', 'Cruzeiro - DF'): 7531,
    ('Lago Sul - DF', 'Samambaia - DF'): 28731,
    ('Lago Sul - DF', 'Santa Maria - DF'): 26548,
    ('Lago Sul - DF', 'São Sebastião - DF'): 19837,
    ('Lago Sul - DF', 'Recanto das Emas - DF'): 30849,
    ('Lago Sul - DF', 'Lago Sul - DF'): 0,
    ('Lago Sul - DF', 'Riacho Fundo I - DF'): 19677,
    ('Lago Sul - DF', 'Lago Norte - DF'): 19852,
    ('Lago Sul - DF', 'Candangolândia - DF'): 12970,
    ('Lago Sul - DF', 'Águas Claras - DF'): 22186,
    ('Lago Sul - DF', 'Riacho Fundo II - DF'): 32340,
    ('Lago Sul - DF', 'Sudoeste/Octogonal - DF'): 15083,
    ('Lago Sul - DF', 'Varjão - DF'): 19072,
    ('Lago Sul - DF', 'Park Way - DF'): 12639,
    ('Lago Sul - DF', 'SCIA - DF'): 17522,
    ('Lago Sul - DF', 'Sobradinho II - DF'): 38681,
    ('Lago Sul - DF', 'Jardim Botânico - DF'): 14907,
    ('Lago Sul - DF', 'Itapoã - DF'): 24833,
    ('Lago Sul - DF', 'SIA - DF'): 7531,
    ('Lago Sul - DF', 'Vicente Pires - DF'): 21389,
    ('Lago Sul - DF', 'Fercal - DF'): 34046,
    ('Lago Sul - DF', 'Sol Nascente/Pôr do Sol - DF'): 9686,
    ('Lago Sul - DF', 'Arniqueiras - DF'): 21190,
    ('Riacho Fundo I - DF', 'Plano Piloto - DF'): 21978,
    ('Riacho Fundo I - DF', 'Gama - DF'): 25297,
    ('Riacho Fundo I - DF', 'Taguatinga - DF'): 11536,
    ('Riacho Fundo I - DF', 'Brazlândia - DF'): 41239,
    ('Riacho Fundo I - DF', 'Sobradinho - DF'): 39290,
    ('Riacho Fundo I - DF', 'Planaltina - DF'): 73662,
    ('Riacho Fundo I - DF', 'Paranoá - DF'): 36745,
    ('Riacho Fundo I - DF', 'Núcleo Bandeirante - DF'): 6267,
    ('Riacho Fundo I - DF', 'Ceilândia - DF'): 18337,
    ('Riacho Fundo I - DF', 'Guará - DF'): 15699,
    ('Riacho Fundo I - DF', 'Cruzeiro - DF'): 21315,
    ('Riacho Fundo I - DF', 'Samambaia - DF'): 11295,
    ('Riacho Fundo I - DF', 'Santa Maria - DF'): 24692,
    ('Riacho Fundo I - DF', 'São Sebastião - DF'): 38520,
    ('Riacho Fundo I - DF', 'Recanto das Emas - DF'): 11693,
    ('Riacho Fundo I - DF', 'Lago Sul - DF'): 20130,
    ('Riacho Fundo I - DF', 'Riacho Fundo I - DF'): 0,
    ('Riacho Fundo I - DF', 'Lago Norte - DF'): 30448,
    ('Riacho Fundo I - DF', 'Candangolândia - DF'): 9199,
    ('Riacho Fundo I - DF', 'Águas Claras - DF'): 8128,
    ('Riacho Fundo I - DF', 'Riacho Fundo II - DF'): 5982,
    ('Riacho Fundo I - DF', 'Sudoeste/Octogonal - DF'): 15336,
    ('Riacho Fundo I - DF', 'Varjão - DF'): 29668,
    ('Riacho Fundo I - DF', 'Park Way - DF'): 10783,
    ('Riacho Fundo I - DF', 'SCIA - DF'): 19926,
    ('Riacho Fundo I - DF', 'Sobradinho II - DF'): 48191,
    ('Riacho Fundo I - DF', 'Jardim Botânico - DF'): 33590,
    ('Riacho Fundo I - DF', 'Itapoã - DF'): 41045,
    ('Riacho Fundo I - DF', 'SIA - DF'): 21315,
    ('Riacho Fundo I - DF', 'Vicente Pires - DF'): 15281,
    ('Riacho Fundo I - DF', 'Fercal - DF'): 43556,
    ('Riacho Fundo I - DF', 'Sol Nascente/Pôr do Sol - DF'): 16818,
    ('Riacho Fundo I - DF', 'Arniqueiras - DF'): 8517,
    ('Lago Norte - DF', 'Plano Piloto - DF'): 14195,
    ('Lago Norte - DF', 'Gama - DF'): 45478,
    ('Lago Norte - DF', 'Taguatinga - DF'): 30095,
    ('Lago Norte - DF', 'Brazlândia - DF'): 54947,
    ('Lago Norte - DF', 'Sobradinho - DF'): 19156,
    ('Lago Norte - DF', 'Planaltina - DF'): 53528,
    ('Lago Norte - DF', 'Paranoá - DF'): 18655,
    ('Lago Norte - DF', 'Núcleo Bandeirante - DF'): 25736,
    ('Lago Norte - DF', 'Ceilândia - DF'): 38489,
    ('Lago Norte - DF', 'Guará - DF'): 25253,
    ('Lago Norte - DF', 'Cruzeiro - DF'): 13571,
    ('Lago Norte - DF', 'Samambaia - DF'): 39536,
    ('Lago Norte - DF', 'Santa Maria - DF'): 40099,
    ('Lago Norte - DF', 'São Sebastião - DF'): 33524,
    ('Lago Norte - DF', 'Recanto das Emas - DF'): 39934,
    ('Lago Norte - DF', 'Lago Sul - DF'): 23908,
    ('Lago Norte - DF', 'Riacho Fundo I - DF'): 30482,
    ('Lago Norte - DF', 'Lago Norte - DF'): 0,
    ('Lago Norte - DF', 'Candangolândia - DF'): 24776,
    ('Lago Norte - DF', 'Águas Claras - DF'): 29308,
    ('Lago Norte - DF', 'Riacho Fundo II - DF'): 38544,
    ('Lago Norte - DF', 'Sudoeste/Octogonal - DF'): 17836,
    ('Lago Norte - DF', 'Varjão - DF'): 5861,
    ('Lago Norte - DF', 'Park Way - DF'): 26190,
    ('Lago Norte - DF', 'SCIA - DF'): 19446,
    ('Lago Norte - DF', 'Sobradinho II - DF'): 28058,
    ('Lago Norte - DF', 'Jardim Botânico - DF'): 28594,
    ('Lago Norte - DF', 'Itapoã - DF'): 20113,
    ('Lago Norte - DF', 'SIA - DF'): 13571,
    ('Lago Norte - DF', 'Vicente Pires - DF'): 26119,
    ('Lago Norte - DF', 'Fercal - DF'): 23422,
    ('Lago Norte - DF', 'Sol Nascente/Pôr do Sol - DF'): 19121,
    ('Lago Norte - DF', 'Arniqueiras - DF'): 29109,
    ('Candangolândia - DF', 'Plano Piloto - DF'): 14198,
    ('Candangolândia - DF', 'Gama - DF'): 24101,
    ('Candangolândia - DF', 'Taguatinga - DF'): 21365,
    ('Candangolândia - DF', 'Brazlândia - DF'): 51163,
    ('Candangolândia - DF', 'Sobradinho - DF'): 31509,
    ('Candangolândia - DF', 'Planaltina - DF'): 65881,
    ('Candangolândia - DF', 'Paranoá - DF'): 28965,
    ('Candangolândia - DF', 'Núcleo Bandeirante - DF'): 4065,
    ('Candangolândia - DF', 'Ceilândia - DF'): 24908,
    ('Candangolândia - DF', 'Guará - DF'): 7918,
    ('Candangolândia - DF', 'Cruzeiro - DF'): 13535,
    ('Candangolândia - DF', 'Samambaia - DF'): 17865,
    ('Candangolândia - DF', 'Santa Maria - DF'): 18721,
    ('Candangolândia - DF', 'São Sebastião - DF'): 30739,
    ('Candangolândia - DF', 'Recanto das Emas - DF'): 18264,
    ('Candangolândia - DF', 'Lago Sul - DF'): 12350,
    ('Candangolândia - DF', 'Riacho Fundo I - DF'): 8811,
    ('Candangolândia - DF', 'Lago Norte - DF'): 22667,
    ('Candangolândia - DF', 'Candangolândia - DF'): 0,
    ('Candangolândia - DF', 'Águas Claras - DF'): 11321,
    ('Candangolândia - DF', 'Riacho Fundo II - DF'): 16873,
    ('Candangolândia - DF', 'Sudoeste/Octogonal - DF'): 7555,
    ('Candangolândia - DF', 'Varjão - DF'): 21887,
    ('Candangolândia - DF', 'Park Way - DF'): 4812,
    ('Candangolândia - DF', 'SCIA - DF'): 11873,
    ('Candangolândia - DF', 'Sobradinho II - DF'): 40411,
    ('Candangolândia - DF', 'Jardim Botânico - DF'): 25809,
    ('Candangolândia - DF', 'Itapoã - DF'): 33264,
    ('Candangolândia - DF', 'SIA - DF'): 13535,
    ('Candangolândia - DF', 'Vicente Pires - DF'): 15620,
    ('Candangolândia - DF', 'Fercal - DF'): 35775,
    ('Candangolândia - DF', 'Sol Nascente/Pôr do Sol - DF'): 9037,
    ('Candangolândia - DF', 'Arniqueiras - DF'): 10325,
    ('Águas Claras - DF', 'Plano Piloto - DF'): 19786,
    ('Águas Claras - DF', 'Gama - DF'): 27007,
    ('Águas Claras - DF', 'Taguatinga - DF'): 6789,
    ('Águas Claras - DF', 'Brazlândia - DF'): 36493,
    ('Águas Claras - DF', 'Sobradinho - DF'): 37589,
    ('Águas Claras - DF', 'Planaltina - DF'): 71961,
    ('Águas Claras - DF', 'Paranoá - DF'): 40761,
    ('Águas Claras - DF', 'Núcleo Bandeirante - DF'): 11927,
    ('Águas Claras - DF', 'Ceilândia - DF'): 12510,
    ('Águas Claras - DF', 'Guará - DF'): 10242,
    ('Águas Claras - DF', 'Cruzeiro - DF'): 22987,
    ('Águas Claras - DF', 'Samambaia - DF'): 13004,
    ('Águas Claras - DF', 'Santa Maria - DF'): 30352,
    ('Águas Claras - DF', 'São Sebastião - DF'): 42289,
    ('Águas Claras - DF', 'Recanto das Emas - DF'): 13402,
    ('Águas Claras - DF', 'Lago Sul - DF'): 23899,
    ('Águas Claras - DF', 'Riacho Fundo I - DF'): 7902,
    ('Águas Claras - DF', 'Lago Norte - DF'): 28747,
    ('Águas Claras - DF', 'Candangolândia - DF'): 14859,
    ('Águas Claras - DF', 'Águas Claras - DF'): 0,
    ('Águas Claras - DF', 'Riacho Fundo II - DF'): 12012,
    ('Águas Claras - DF', 'Sudoeste/Octogonal - DF'): 13635,
    ('Águas Claras - DF', 'Varjão - DF'): 27967,
    ('Águas Claras - DF', 'Park Way - DF'): 16443,
    ('Águas Claras - DF', 'SCIA - DF'): 11451,
    ('Águas Claras - DF', 'Sobradinho II - DF'): 46490,
    ('Águas Claras - DF', 'Jardim Botânico - DF'): 37359,
    ('Águas Claras - DF', 'Itapoã - DF'): 43074,
    ('Águas Claras - DF', 'SIA - DF'): 22987,
    ('Águas Claras - DF', 'Vicente Pires - DF'): 6806,
    ('Águas Claras - DF', 'Fercal - DF'): 41855,
    ('Águas Claras - DF', 'Sol Nascente/Pôr do Sol - DF'): 17034,
    ('Águas Claras - DF', 'Arniqueiras - DF'): 1723,
    ('Riacho Fundo II - DF', 'Plano Piloto - DF'): 28896,
    ('Riacho Fundo II - DF', 'Gama - DF'): 17701,
    ('Riacho Fundo II - DF', 'Taguatinga - DF'): 16058,
    ('Riacho Fundo II - DF', 'Brazlândia - DF'): 45762,
    ('Riacho Fundo II - DF', 'Sobradinho - DF'): 46207,
    ('Riacho Fundo II - DF', 'Planaltina - DF'): 80579,
    ('Riacho Fundo II - DF', 'Paranoá - DF'): 43663,
    ('Riacho Fundo II - DF', 'Núcleo Bandeirante - DF'): 13185,
    ('Riacho Fundo II - DF', 'Ceilândia - DF'): 15490,
    ('Riacho Fundo II - DF', 'Guará - DF'): 22616,
    ('Riacho Fundo II - DF', 'Cruzeiro - DF'): 28233,
    ('Riacho Fundo II - DF', 'Samambaia - DF'): 8447,
    ('Riacho Fundo II - DF', 'Santa Maria - DF'): 16707,
    ('Riacho Fundo II - DF', 'São Sebastião - DF'): 44151,
    ('Riacho Fundo II - DF', 'Recanto das Emas - DF'): 4097,
    ('Riacho Fundo II - DF', 'Lago Sul - DF'): 27048,
    ('Riacho Fundo II - DF', 'Riacho Fundo I - DF'): 8530,
    ('Riacho Fundo II - DF', 'Lago Norte - DF'): 37365,
    ('Riacho Fundo II - DF', 'Candangolândia - DF'): 16117,
    ('Riacho Fundo II - DF', 'Águas Claras - DF'): 13070,
    ('Riacho Fundo II - DF', 'Riacho Fundo II - DF'): 0,
    ('Riacho Fundo II - DF', 'Sudoeste/Octogonal - DF'): 22254,
    ('Riacho Fundo II - DF', 'Varjão - DF'): 36585,
    ('Riacho Fundo II - DF', 'Park Way - DF'): 17701,
    ('Riacho Fundo II - DF', 'SCIA - DF'): 24048,
    ('Riacho Fundo II - DF', 'Sobradinho II - DF'): 55109,
    ('Riacho Fundo II - DF', 'Jardim Botânico - DF'): 44105,
    ('Riacho Fundo II - DF', 'Itapoã - DF'): 47962,
    ('Riacho Fundo II - DF', 'SIA - DF'): 28233,
    ('Riacho Fundo II - DF', 'Vicente Pires - DF'): 20428,
    ('Riacho Fundo II - DF', 'Fercal - DF'): 50473,
    ('Riacho Fundo II - DF', 'Sol Nascente/Pôr do Sol - DF'): 23735,
    ('Riacho Fundo II - DF', 'Arniqueiras - DF'): 13781,
    ('Sudoeste/Octogonal - DF', 'Plano Piloto - DF'): 8791,
    ('Sudoeste/Octogonal - DF', 'Gama - DF'): 31809,
    ('Sudoeste/Octogonal - DF', 'Taguatinga - DF'): 18443,
    ('Sudoeste/Octogonal - DF', 'Brazlândia - DF'): 44962,
    ('Sudoeste/Octogonal - DF', 'Sobradinho - DF'): 25308,
    ('Sudoeste/Octogonal - DF', 'Planaltina - DF'): 59680,
    ('Sudoeste/Octogonal - DF', 'Paranoá - DF'): 28480,
    ('Sudoeste/Octogonal - DF', 'Núcleo Bandeirante - DF'): 12067,
    ('Sudoeste/Octogonal - DF', 'Ceilândia - DF'): 24127,
    ('Sudoeste/Octogonal - DF', 'Guará - DF'): 9076,
    ('Sudoeste/Octogonal - DF', 'Cruzeiro - DF'): 10274,
    ('Sudoeste/Octogonal - DF', 'Samambaia - DF'): 23816,
    ('Sudoeste/Octogonal - DF', 'Santa Maria - DF'): 26430,
    ('Sudoeste/Octogonal - DF', 'São Sebastião - DF'): 32517,
    ('Sudoeste/Octogonal - DF', 'Recanto das Emas - DF'): 26265,
    ('Sudoeste/Octogonal - DF', 'Lago Sul - DF'): 14128,
    ('Sudoeste/Octogonal - DF', 'Riacho Fundo I - DF'): 16813,
    ('Sudoeste/Octogonal - DF', 'Lago Norte - DF'): 16466,
    ('Sudoeste/Octogonal - DF', 'Candangolândia - DF'): 11107,
    ('Sudoeste/Octogonal - DF', 'Águas Claras - DF'): 14587,
    ('Sudoeste/Octogonal - DF', 'Riacho Fundo II - DF'): 24875,
    ('Sudoeste/Octogonal - DF', 'Sudoeste / Octogonal - DF'): 0,
    ('Sudoeste/Octogonal - DF', 'Varjão - DF'): 15686,
    ('Sudoeste/Octogonal - DF', 'Park Way - DF'): 12521,
    ('Sudoeste/Octogonal - DF', 'SCIA - DF'): 9460,
    ('Sudoeste/Octogonal - DF', 'Sobradinho II - DF'): 34210,
    ('Sudoeste/Octogonal - DF', 'Jardim Botânico - DF'): 27588,
    ('Sudoeste/Octogonal - DF', 'Itapoã - DF'): 30794,
    ('Sudoeste/Octogonal - DF', 'SIA - DF'): 10274,
    ('Sudoeste/Octogonal - DF', 'Vicente Pires - DF'): 12699,
    ('Sudoeste/Octogonal - DF', 'Fercal - DF'): 29574,
    ('Sudoeste/Octogonal - DF', 'Sol Nascente/Pôr do Sol - DF'): 7263,
    ('Sudoeste/Octogonal - DF', 'Arniqueiras - DF'): 14388,
    ('Varjão - DF', 'Plano Piloto - DF'): 13730,
    ('Varjão - DF', 'Gama - DF'): 45013,
    ('Varjão - DF', 'Taguatinga - DF'): 29630,
    ('Varjão - DF', 'Brazlândia - DF'): 54482,
    ('Varjão - DF', 'Sobradinho - DF'): 18378,
    ('Varjão - DF', 'Planaltina - DF'): 52750,
    ('Varjão - DF', 'Paranoá - DF'): 15244,
    ('Varjão - DF', 'Núcleo Bandeirante - DF'): 25271,
    ('Varjão - DF', 'Ceilândia - DF'): 38024,
    ('Varjão - DF', 'Guará - DF'): 24788,
    ('Varjão - DF', 'Cruzeiro - DF'): 13106,
    ('Varjão - DF', 'Samambaia - DF'): 39071,
    ('Varjão - DF', 'Santa Maria - DF'): 39634,
    ('Varjão - DF', 'São Sebastião - DF'): 33059,
    ('Varjão - DF', 'Recanto das Emas - DF'): 39469,
    ('Varjão - DF', 'Lago Sul - DF'): 23443,
    ('Varjão - DF', 'Riacho Fundo I - DF'): 30017,
    ('Varjão - DF', 'Lago Norte - DF'): 6918,
    ('Varjão - DF', 'Candangolândia - DF'): 24311,
    ('Varjão - DF', 'Águas Claras - DF'): 28843,
    ('Varjão - DF', 'Riacho Fundo II - DF'): 38079,
    ('Varjão - DF', 'Sudoeste/Octogonal - DF'): 17371,
    ('Varjão - DF', 'Varjão - DF'): 0,
    ('Varjão - DF', 'Park Way - DF'): 25725,
    ('Varjão - DF', 'SCIA - DF'): 18981,
    ('Varjão - DF', 'Sobradinho II - DF'): 27279,
    ('Varjão - DF', 'Jardim Botânico - DF'): 28129,
    ('Varjão - DF', 'Itapoã - DF'): 16703,
    ('Varjão - DF', 'SIA - DF'): 13106,
    ('Varjão - DF', 'Vicente Pires - DF'): 25654,
    ('Varjão - DF', 'Fercal - DF'): 22644,
    ('Varjão - DF', 'Sol Nascente/Pôr do Sol - DF'): 18656,
    ('Varjão - DF', 'Arniqueiras - DF'): 28644,
    ('Park Way - DF', 'Plano Piloto - DF'): 15120,
    ('Park Way - DF', 'Gama - DF'): 19288,
    ('Park Way - DF', 'Taguatinga - DF'): 24340,
    ('Park Way - DF', 'Brazlândia - DF'): 54137,
    ('Park Way - DF', 'Sobradinho - DF'): 34484,
    ('Park Way - DF', 'Planaltina - DF'): 68856,
    ('Park Way - DF', 'Paranoá - DF'): 30458,
    ('Park Way - DF', 'Núcleo Bandeirante - DF'): 4600,
    ('Park Way - DF', 'Ceilândia - DF'): 27280,
    ('Park Way - DF', 'Guará - DF'): 10893,
    ('Park Way - DF', 'Cruzeiro - DF'): 14457,
    ('Park Way - DF', 'Samambaia - DF'): 20237,
    ('Park Way - DF', 'Santa Maria - DF'): 13909,
    ('Park Way - DF', 'São Sebastião - DF'): 28612,
    ('Park Way - DF', 'Recanto das Emas - DF'): 18211,
    ('Park Way - DF', 'Lago Sul - DF'): 12181,
    ('Park Way - DF', 'Riacho Fundo I - DF'): 11183,
    ('Park Way - DF', 'Lago Norte - DF'): 25642,
    ('Park Way - DF', 'Candangolândia - DF'): 4476,
    ('Park Way - DF', 'Águas Claras - DF'): 13692,
    ('Park Way - DF', 'Riacho Fundo II - DF'): 19701,
    ('Park Way - DF', 'Sudoeste/Octogonal - DF'): 10530,
    ('Park Way - DF', 'Varjão - DF'): 24862,
    ('Park Way - DF', 'Park Way - DF'): 0,
    ('Park Way - DF', 'SCIA - DF'): 14848,
    ('Park Way - DF', 'Sobradinho II - DF'): 43385,
    ('Park Way - DF', 'Jardim Botânico - DF'): 23683,
    ('Park Way - DF', 'Itapoã - DF'): 34757,
    ('Park Way - DF', 'SIA - DF'): 14457,
    ('Park Way - DF', 'Vicente Pires - DF'): 18595,
    ('Park Way - DF', 'Fercal - DF'): 38750,
    ('Park Way - DF', 'Sol Nascente/Pôr do Sol - DF'): 9960,
    ('Park Way - DF', 'Arniqueiras - DF'): 12697,
    ('SCIA - DF', 'Plano Piloto - DF'): 13441,
    ('SCIA - DF', 'Gama - DF'): 34136,
    ('SCIA - DF', 'Taguatinga - DF'): 12063,
    ('SCIA - DF', 'Brazlândia - DF'): 36915,
    ('SCIA - DF', 'Sobradinho - DF'): 28847,
    ('SCIA - DF', 'Planaltina - DF'): 63219,
    ('SCIA - DF', 'Paranoá - DF'): 32019,
    ('SCIA - DF', 'Núcleo Bandeirante - DF'): 14394,
    ('SCIA - DF', 'Ceilândia - DF'): 20458,
    ('SCIA - DF', 'Guará - DF'): 6728,
    ('SCIA - DF', 'Cruzeiro - DF'): 14275,
    ('SCIA - DF', 'Samambaia - DF'): 20511,
    ('SCIA - DF', 'Santa Maria - DF'): 28757,
    ('SCIA - DF', 'São Sebastião - DF'): 34238,
    ('SCIA - DF', 'Recanto das Emas - DF'): 25042,
    ('SCIA - DF', 'Lago Sul - DF'): 19665,
    ('SCIA - DF', 'Riacho Fundo I - DF'): 19542,
    ('SCIA - DF', 'Lago Norte - DF'): 20005,
    ('SCIA - DF', 'Candangolândia - DF'): 13434,
    ('SCIA - DF', 'Águas Claras - DF'): 11276,
    ('SCIA - DF', 'Riacho Fundo II - DF'): 23652,
    ('SCIA - DF', 'Sudoeste/Octogonal - DF'): 6494,
    ('SCIA - DF', 'Varjão - DF'): 19225,
    ('SCIA - DF', 'Park Way - DF'): 14848,
    ('SCIA - DF', 'SCIA - DF'): 0,
    ('SCIA - DF', 'Sobradinho II - DF'): 37748,
    ('SCIA - DF', 'Jardim Botânico - DF'): 29308,
    ('SCIA - DF', 'Itapoã - DF'): 34332,
    ('SCIA - DF', 'SIA - DF'): 14275,
    ('SCIA - DF', 'Vicente Pires - DF'): 8087,
    ('SCIA - DF', 'Fercal - DF'): 33113,
    ('SCIA - DF', 'Sol Nascente/Pôr do Sol - DF'): 11453,
    ('SCIA - DF', 'Arniqueiras - DF'): 11077,
    ('Sobradinho II - DF', 'Plano Piloto - DF'): 32600,
    ('Sobradinho II - DF', 'Gama - DF'): 62391,
    ('Sobradinho II - DF', 'Taguatinga - DF'): 47008,
    ('Sobradinho II - DF', 'Brazlândia - DF'): 71860,
    ('Sobradinho II - DF', 'Sobradinho - DF'): 11001,
    ('Sobradinho II - DF', 'Planaltina - DF'): 47004,
    ('Sobradinho II - DF', 'Paranoá - DF'): 29898,
    ('Sobradinho II - DF', 'Núcleo Bandeirante - DF'): 42649,
    ('Sobradinho II - DF', 'Ceilândia - DF'): 55402,
    ('Sobradinho II - DF', 'Guará - DF'): 42166,
    ('Sobradinho II - DF', 'Cruzeiro - DF'): 31975,
    ('Sobradinho II - DF', 'Samambaia - DF'): 56449,
    ('Sobradinho II - DF', 'Santa Maria - DF'): 57012,
    ('Sobradinho II - DF', 'São Sebastião - DF'): 51929,
    ('Sobradinho II - DF', 'Recanto das Emas - DF'): 56847,
    ('Sobradinho II - DF', 'Lago Sul - DF'): 42312,
    ('Sobradinho II - DF', 'Riacho Fundo I - DF'): 47395,
    ('Sobradinho II - DF', 'Lago Norte - DF'): 28582,
    ('Sobradinho II - DF', 'Candangolândia - DF'): 41689,
    ('Sobradinho II - DF', 'Águas Claras - DF'): 46221,
    ('Sobradinho II - DF', 'Riacho Fundo II - DF'): 55457,
    ('Sobradinho II - DF', 'Sudoeste/Octogonal - DF'): 34749,
    ('Sobradinho II - DF', 'Varjão - DF'): 23401,
    ('Sobradinho II - DF', 'Park Way - DF'): 43103,
    ('Sobradinho II - DF', 'SCIA - DF'): 36359,
    ('Sobradinho II - DF', 'Sobradinho II - DF'): 0,
    ('Sobradinho II - DF', 'Jardim Botânico - DF'): 46999,
    ('Sobradinho II - DF', 'Itapoã - DF'): 27179,
    ('Sobradinho II - DF', 'SIA - DF'): 31975,
    ('Sobradinho II - DF', 'Vicente Pires - DF'): 43032,
    ('Sobradinho II - DF', 'Fercal - DF'): 15191,
    ('Sobradinho II - DF', 'Sol Nascente/Pôr do Sol - DF'): 39708,
    ('Sobradinho II - DF', 'Arniqueiras - DF'): 46022,
    ('Jardim Botânico - DF', 'Plano Piloto - DF'): 16562,
    ('Jardim Botânico - DF', 'Gama - DF'): 42838,
    ('Jardim Botânico - DF', 'Taguatinga - DF'): 40886,
    ('Jardim Botânico - DF', 'Brazlândia - DF'): 65271,
    ('Jardim Botânico - DF', 'Sobradinho - DF'): 37423,
    ('Jardim Botânico - DF', 'Planaltina - DF'): 71795,
    ('Jardim Botânico - DF', 'Paranoá - DF'): 16864,
    ('Jardim Botânico - DF', 'Núcleo Bandeirante - DF'): 25166,
    ('Jardim Botânico - DF', 'Ceilândia - DF'): 46570,
    ('Jardim Botânico - DF', 'Guará - DF'): 28944,
    ('Jardim Botânico - DF', 'Cruzeiro - DF'): 16484,
    ('Jardim Botânico - DF', 'Samambaia - DF'): 43457,
    ('Jardim Botânico - DF', 'Santa Maria - DF'): 33895,
    ('Jardim Botânico - DF', 'São Sebastião - DF'): 11583,
    ('Jardim Botânico - DF', 'Recanto das Emas - DF'): 41557,
    ('Jardim Botânico - DF', 'Lago Sul - DF'): 13570,
    ('Jardim Botânico - DF', 'Riacho Fundo I - DF'): 34403,
    ('Jardim Botânico - DF', 'Lago Norte - DF'): 27495,
    ('Jardim Botânico - DF', 'Candangolândia - DF'): 28698,
    ('Jardim Botânico - DF', 'Águas Claras - DF'): 37031,
    ('Jardim Botânico - DF', 'Riacho Fundo II - DF'): 43048,
    ('Jardim Botânico - DF', 'Sudoeste/Octogonal - DF'): 28836,
    ('Jardim Botânico - DF', 'Varjão - DF'): 26715,
    ('Jardim Botânico - DF', 'Park Way - DF'): 30111,
    ('Jardim Botânico - DF', 'SCIA - DF'): 29769,
    ('Jardim Botânico - DF', 'Sobradinho II - DF'): 46324,
    ('Jardim Botânico - DF', 'Jardim Botânico - DF'): 0,
    ('Jardim Botânico - DF', 'Itapoã - DF'): 21163,
    ('Jardim Botânico - DF', 'SIA - DF'): 16484,
    ('Jardim Botânico - DF', 'Vicente Pires - DF'): 35142,
    ('Jardim Botânico - DF', 'Fercal - DF'): 41689,
    ('Jardim Botânico - DF', 'Sol Nascente/Pôr do Sol - DF'): 23438,
    ('Jardim Botânico - DF', 'Arniqueiras - DF'): 35917,
    ('Itapoã - DF', 'Plano Piloto - DF'): 24215,
    ('Itapoã - DF', 'Gama - DF'): 58211,
    ('Itapoã - DF', 'Taguatinga - DF'): 44383,
    ('Itapoã - DF', 'Brazlândia - DF'): 69235,
    ('Itapoã - DF', 'Sobradinho - DF'): 18275,
    ('Itapoã - DF', 'Planaltina - DF'): 45624,
    ('Itapoã - DF', 'Paranoá - DF'): 6441,
    ('Itapoã - DF', 'Núcleo Bandeirante - DF'): 37221,
    ('Itapoã - DF', 'Ceilândia - DF'): 52778,
    ('Itapoã - DF', 'Guará - DF'): 36597,
    ('Itapoã - DF', 'Cruzeiro - DF'): 24137,
    ('Itapoã - DF', 'Samambaia - DF'): 51110,
    ('Itapoã - DF', 'Santa Maria - DF'): 49269,
    ('Itapoã - DF', 'São Sebastião - DF'): 26956,
    ('Itapoã - DF', 'Recanto das Emas - DF'): 56930,
    ('Itapoã - DF', 'Lago Sul - DF'): 23901,
    ('Itapoã - DF', 'Riacho Fundo I - DF'): 42056,
    ('Itapoã - DF', 'Lago Norte - DF'): 20764,
    ('Itapoã - DF', 'Candangolândia - DF'): 36351,
    ('Itapoã - DF', 'Águas Claras - DF'): 43597,
    ('Itapoã - DF', 'Riacho Fundo II - DF'): 58421,
    ('Itapoã - DF', 'Sudoeste/Octogonal - DF'): 32125,
    ('Itapoã - DF', 'Varjão - DF'): 15837,
    ('Itapoã - DF', 'Park Way - DF'): 37764,
    ('Itapoã - DF', 'SCIA - DF'): 33734,
    ('Itapoã - DF', 'Sobradinho II - DF'): 27177,
    ('Itapoã - DF', 'Jardim Botânico - DF'): 22026,
    ('Itapoã - DF', 'Itapoã - DF'): 0,
    ('Itapoã - DF', 'SIA - DF'): 24137,
    ('Itapoã - DF', 'Vicente Pires - DF'): 40407,
    ('Itapoã - DF', 'Fercal - DF'): 26066,
    ('Itapoã - DF', 'Sol Nascente/Pôr do Sol - DF'): 31091,
    ('Itapoã - DF', 'Arniqueiras - DF'): 43398,
    ('SIA - DF', 'Plano Piloto - DF'): 2252,
    ('SIA - DF', 'Gama - DF'): 35011,
    ('SIA - DF', 'Taguatinga - DF'): 24775,
    ('SIA - DF', 'Brazlândia - DF'): 49627,
    ('SIA - DF', 'Sobradinho - DF'): 23008,
    ('SIA - DF', 'Planaltina - DF'): 57380,
    ('SIA - DF', 'Paranoá - DF'): 21446,
    ('SIA - DF', 'Núcleo Bandeirante - DF'): 16024,
    ('SIA - DF', 'Ceilândia - DF'): 33170,
    ('SIA - DF', 'Guará - DF'): 15820,
    ('SIA - DF', 'Cruzeiro - DF'): 0,
    ('SIA - DF', 'Samambaia - DF'): 30333,
    ('SIA - DF', 'Santa Maria - DF'): 29632,
    ('SIA - DF', 'São Sebastião - DF'): 23221,
    ('SIA - DF', 'Recanto das Emas - DF'): 33934,
    ('SIA - DF', 'Lago Sul - DF'): 9522,
    ('SIA - DF', 'Riacho Fundo I - DF'): 21279,
    ('SIA - DF', 'Lago Norte - DF'): 13080,
    ('SIA - DF', 'Candangolândia - DF'): 16054,
    ('SIA - DF', 'Águas Claras - DF'): 22658,
    ('SIA - DF', 'Riacho Fundo II - DF'): 35424,
    ('SIA - DF', 'Sudoeste/Octogonal - DF'): 12558,
    ('SIA - DF', 'Varjão - DF'): 12300,
    ('SIA - DF', 'Park Way - DF'): 15723,
    ('SIA - DF', 'SCIA - DF'): 14126,
    ('SIA - DF', 'Sobradinho II - DF'): 31909,
    ('SIA - DF', 'Jardim Botânico - DF'): 18291,
    ('SIA - DF', 'Itapoã - DF'): 26553,
    ('SIA - DF', 'SIA - DF'): 0,
    ('SIA - DF', 'Vicente Pires - DF'): 20769,
    ('SIA - DF', 'Fercal - DF'): 27274,
    ('SIA - DF', 'Sol Nascente/Pôr do Sol - DF'): 6878,
    ('SIA - DF', 'Arniqueiras - DF'): 22459,
    ('Vicente Pires - DF', 'Plano Piloto - DF'): 17599,
    ('Vicente Pires - DF', 'Gama - DF'): 37773,
    ('Vicente Pires - DF', 'Taguatinga - DF'): 6376,
    ('Vicente Pires - DF', 'Brazlândia - DF'): 34744,
    ('Vicente Pires - DF', 'Sobradinho - DF'): 33005,
    ('Vicente Pires - DF', 'Planaltina - DF'): 67377,
    ('Vicente Pires - DF', 'Paranoá - DF'): 36177,
    ('Vicente Pires - DF', 'Núcleo Bandeirante - DF'): 12918,
    ('Vicente Pires - DF', 'Ceilândia - DF'): 15596,
    ('Vicente Pires - DF', 'Guará - DF'): 8095,
    ('Vicente Pires - DF', 'Cruzeiro - DF'): 18434,
    ('Vicente Pires - DF', 'Samambaia - DF'): 15286,
    ('Vicente Pires - DF', 'Santa Maria - DF'): 32394,
    ('Vicente Pires - DF', 'São Sebastião - DF'): 38396,
    ('Vicente Pires - DF', 'Recanto das Emas - DF'): 19816,
    ('Vicente Pires - DF', 'Lago Sul - DF'): 21752,
    ('Vicente Pires - DF', 'Riacho Fundo I - DF'): 14235,
    ('Vicente Pires - DF', 'Lago Norte - DF'): 24163,
    ('Vicente Pires - DF', 'Candangolândia - DF'): 17071,
    ('Vicente Pires - DF', 'Águas Claras - DF'): 6046,
    ('Vicente Pires - DF', 'Riacho Fundo II - DF'): 18426,
    ('Vicente Pires - DF', 'Sudoeste/Octogonal - DF'): 11488,
    ('Vicente Pires - DF', 'Varjão - DF'): 23383,
    ('Vicente Pires - DF', 'Park Way - DF'): 18485,
    ('Vicente Pires - DF', 'SCIA - DF'): 6749,
    ('Vicente Pires - DF', 'Sobradinho II - DF'): 41906,
    ('Vicente Pires - DF', 'Jardim Botânico - DF'): 33466,
    ('Vicente Pires - DF', 'Itapoã - DF'): 38491,
    ('Vicente Pires - DF', 'SIA - DF'): 18434,
    ('Vicente Pires - DF', 'Vicente Pires - DF'): 0,
    ('Vicente Pires - DF', 'Fercal - DF'): 37271,
    ('Vicente Pires - DF', 'Sol Nascente/Pôr do Sol - DF'): 14887,
    ('Vicente Pires - DF', 'Arniqueiras - DF'): 5847,
    ('Fercal - DF', 'Plano Piloto - DF'): 28054,
    ('Fercal - DF', 'Gama - DF'): 57845,
    ('Fercal - DF', 'Taguatinga - DF'): 42462,
    ('Fercal - DF', 'Brazlândia - DF'): 67314,
    ('Fercal - DF', 'Sobradinho - DF'): 15194,
    ('Fercal - DF', 'Planaltina - DF'): 49566,
    ('Fercal - DF', 'Paranoá - DF'): 29101,
    ('Fercal - DF', 'Núcleo Bandeirante - DF'): 38103,
    ('Fercal - DF', 'Ceilândia - DF'): 50856,
    ('Fercal - DF', 'Guará - DF'): 37620,
    ('Fercal - DF', 'Cruzeiro - DF'): 27429,
    ('Fercal - DF', 'Samambaia - DF'): 51903,
    ('Fercal - DF', 'Santa Maria - DF'): 52466,
    ('Fercal - DF', 'São Sebastião - DF'): 47382,
    ('Fercal - DF', 'Recanto das Emas - DF'): 52301,
    ('Fercal - DF', 'Lago Sul - DF'): 37766,
    ('Fercal - DF', 'Riacho Fundo I - DF'): 42849,
    ('Fercal - DF', 'Lago Norte - DF'): 24036,
    ('Fercal - DF', 'Candangolândia - DF'): 37143,
    ('Fercal - DF', 'Águas Claras - DF'): 41675,
    ('Fercal - DF', 'Riacho Fundo II - DF'): 50911,
    ('Fercal - DF', 'Sudoeste/Octogonal - DF'): 30203,
    ('Fercal - DF', 'Varjão - DF'): 18855,
    ('Fercal - DF', 'Park Way - DF'): 38557,
    ('Fercal - DF', 'SCIA - DF'): 31813,
    ('Fercal - DF', 'Sobradinho II - DF'): 16140,
    ('Fercal - DF', 'Jardim Botânico - DF'): 42453,
    ('Fercal - DF', 'Itapoã - DF'): 26382,
    ('Fercal - DF', 'SIA - DF'): 27429,
    ('Fercal - DF', 'Vicente Pires - DF'): 38486,
    ('Fercal - DF', 'Fercal - DF'): 0,
    ('Fercal - DF', 'Sol Nascente/Pôr do Sol - DF'): 35162,
    ('Fercal - DF', 'Arniqueiras - DF'): 41476,
    ('Sol Nascente/Pôr do Sol - DF', 'Plano Piloto - DF'): 6294,
    ('Sol Nascente/Pôr do Sol - DF', 'Gama - DF'): 29414,
    ('Sol Nascente/Pôr do Sol - DF', 'Taguatinga - DF'): 20181,
    ('Sol Nascente/Pôr do Sol - DF', 'Brazlândia - DF'): 48453,
    ('Sol Nascente/Pôr do Sol - DF', 'Sobradinho - DF'): 30458,
    ('Sol Nascente/Pôr do Sol - DF', 'Planaltina - DF'): 64830,
    ('Sol Nascente/Pôr do Sol - DF', 'Paranoá - DF'): 24507,
    ('Sol Nascente/Pôr do Sol - DF', 'Núcleo Bandeirante - DF'): 10427,
    ('Sol Nascente/Pôr do Sol - DF', 'Ceilândia - DF'): 25865,
    ('Sol Nascente/Pôr do Sol - DF', 'Guará - DF'): 10222,
    ('Sol Nascente/Pôr do Sol - DF', 'Cruzeiro - DF'): 6442,
    ('Sol Nascente/Pôr do Sol - DF', 'Samambaia - DF'): 24736,
    ('Sol Nascente/Pôr do Sol - DF', 'Santa Maria - DF'): 24035,
    ('Sol Nascente/Pôr do Sol - DF', 'São Sebastião - DF'): 26282,
    ('Sol Nascente/Pôr do Sol - DF', 'Recanto das Emas - DF'): 28336,
    ('Sol Nascente/Pôr do Sol - DF', 'Lago Sul - DF'): 7909,
    ('Sol Nascente/Pôr do Sol - DF', 'Riacho Fundo I - DF'): 15681,
    ('Sol Nascente/Pôr do Sol - DF', 'Lago Norte - DF'): 19249,
    ('Sol Nascente/Pôr do Sol - DF', 'Candangolândia - DF'): 10457,
    ('Sol Nascente/Pôr do Sol - DF', 'Águas Claras - DF'): 16326,
    ('Sol Nascente/Pôr do Sol - DF', 'Riacho Fundo II - DF'): 29827,
    ('Sol Nascente/Pôr do Sol - DF', 'Sudoeste/Octogonal - DF'): 6504,
    ('Sol Nascente/Pôr do Sol - DF', 'Varjão - DF'): 18469,
    ('Sol Nascente/Pôr do Sol - DF', 'Park Way - DF'): 10126,
    ('Sol Nascente/Pôr do Sol - DF', 'SCIA - DF'): 10570,
    ('Sol Nascente/Pôr do Sol - DF', 'Sobradinho II - DF'): 39360,
    ('Sol Nascente/Pôr do Sol - DF', 'Jardim Botânico - DF'): 21352,
    ('Sol Nascente/Pôr do Sol - DF', 'Itapoã - DF'): 28807,
    ('Sol Nascente/Pôr do Sol - DF', 'SIA - DF'): 6442,
    ('Sol Nascente/Pôr do Sol - DF', 'Vicente Pires - DF'): 14437,
    ('Sol Nascente/Pôr do Sol - DF', 'Fercal - DF'): 34724,
    ('Sol Nascente/Pôr do Sol - DF', 'Sol Nascente/Pôr do Sol - DF'): 0,
    ('Sol Nascente/Pôr do Sol - DF', 'Arniqueiras - DF'): 16127,
    ('Arniqueiras - DF', 'Plano Piloto - DF'): 18996,
    ('Arniqueiras - DF', 'Gama - DF'): 33655,
    ('Arniqueiras - DF', 'Taguatinga - DF'): 7686,
    ('Arniqueiras - DF', 'Brazlândia - DF'): 37390,
    ('Arniqueiras - DF', 'Sobradinho - DF'): 36798,
    ('Arniqueiras - DF', 'Planaltina - DF'): 71171,
    ('Arniqueiras - DF', 'Paranoá - DF'): 39971,
    ('Arniqueiras - DF', 'Núcleo Bandeirante - DF'): 9851,
    ('Arniqueiras - DF', 'Ceilândia - DF'): 13407,
    ('Arniqueiras - DF', 'Guará - DF'): 9451,
    ('Arniqueiras - DF', 'Cruzeiro - DF'): 22197,
    ('Arniqueiras - DF', 'Samambaia - DF'): 13875,
    ('Arniqueiras - DF', 'Santa Maria - DF'): 28276,
    ('Arniqueiras - DF', 'São Sebastião - DF'): 40465,
    ('Arniqueiras - DF', 'Recanto das Emas - DF'): 14273,
    ('Arniqueiras - DF', 'Lago Sul - DF'): 22076,
    ('Arniqueiras - DF', 'Riacho Fundo I - DF'): 8773,
    ('Arniqueiras - DF', 'Lago Norte - DF'): 27957,
    ('Arniqueiras - DF', 'Candangolândia - DF'): 12783,
    ('Arniqueiras - DF', 'Águas Claras - DF'): 1247,
    ('Arniqueiras - DF', 'Riacho Fundo II - DF'): 12883,
    ('Arniqueiras - DF', 'Sudoeste/Octogonal - DF'): 12845,
    ('Arniqueiras - DF', 'Varjão - DF'): 27177,
    ('Arniqueiras - DF', 'Park Way - DF'): 14367,
    ('Arniqueiras - DF', 'SCIA - DF'): 10985,
    ('Arniqueiras - DF', 'Sobradinho II - DF'): 45700,
    ('Arniqueiras - DF', 'Jardim Botânico - DF'): 35536,
    ('Arniqueiras - DF', 'Itapoã - DF'): 42284,
    ('Arniqueiras - DF', 'SIA - DF'): 22197,
    ('Arniqueiras - DF', 'Vicente Pires - DF'): 6340,
    ('Arniqueiras - DF', 'Fercal - DF'): 41065,
    ('Arniqueiras - DF', 'Sol Nascente/Pôr do Sol - DF'): 16244,
    ('Arniqueiras - DF', 'Arniqueiras - DF'): 0,
}
