import pandas as pd


df = pd.read_excel('dadospmu2.xlsx')
df['distancia'] = df.apply(lambda linha: dataras[(linha['RA_origem'], linha['RA_destino'])], axis=1)


df.drop('fexp_viagem_ajustado', axis = 1, inplace=True)
df.drop('fexp_viagem', axis = 1, inplace=True)
df.drop('outros', axis = 1, inplace=True)
df.drop('ti_publico', axis = 1, inplace=True)
df.drop('ti_privado', axis = 1, inplace=True)
df.drop('tc_privado', axis = 1, inplace=True)
df.drop('tc_publico', axis = 1, inplace=True)
df.drop('ta_bicicleta', axis = 1, inplace=True)
df.drop('ta_ape', axis = 1, inplace=True)
df.drop('usa_tc', axis = 1, inplace=True)
df.drop('usa_ti', axis = 1, inplace=True)
df.drop('usa_modo_outros', axis = 1, inplace=True)
df.drop('usa_ta', axis = 1, inplace=True)
df.drop('usa_modo_servicoprivadomotorista', axis = 1, inplace=True)
df.drop('usa_modo_mototaxi', axis = 1, inplace=True)
df.drop('usa_modo_taxiauto', axis = 1, inplace=True)
df.drop('usa_modo_motopassageiro', axis = 1, inplace=True)
df.drop('usa_modo_motocondutor', axis = 1, inplace=True)
df.drop('usa_modo_automovelcondutor', axis = 1, inplace=True)
df.drop('usa_modo_automovelpassageiro', axis = 1, inplace=True)
df.drop('usa_modo_escolar', axis = 1, inplace=True)
df.drop('usa_modo_coletivo_pirata', axis = 1, inplace=True)
df.drop('usa_modo_fretado', axis = 1, inplace=True)
df.drop('usa_modo_onibus_conv', axis = 1, inplace=True)
df.drop('usa_modo_metro', axis = 1, inplace=True)
df.drop('usa_modo_onibus_brt', axis = 1, inplace=True)
df.drop('usa_modo_bicicleta', axis = 1, inplace=True)
df.drop('usa_modo_ape', axis = 1, inplace=True)
df.drop('motivoViagem_Consolidado_Agregado', axis = 1, inplace=True)
df.drop('motivoViagem_Consolidado', axis = 1, inplace=True)
df.drop('motivoViagem_Agregado', axis = 1, inplace=True)
df.drop('motivoOrigemOutraPessoa', axis = 1, inplace=True)
df.drop('motivoDestinoOutraPessoa', axis = 1, inplace=True)
df.drop('ztorigem', axis = 1, inplace=True)
df.drop('ztdestino', axis = 1, inplace=True)


df.to_excel('dpmu2.xlsx')
